[project]
name = "etl-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymongo>=4.11.2",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
